version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "4500:4500"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  db_data:
